"""Shared Roundcube routing for managed domains."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from ..config import get_settings, load_features


def _dynamic_config_path() -> Path:
    install_root = get_settings().stacks_dir.parent
    return install_root / "compose" / "traefik" / "dynamic" / "webmail.yml"


def _router_name(hostname: str) -> str:
    safe = re.sub(r"[^a-z0-9-]+", "-", hostname.lower()).strip("-")
    return f"webmail-{safe}"[:63]


def routed_hostnames() -> list[str]:
    """Return managed domains and deployed site hostnames."""
    from .domains import list_domains
    from .sites import list_sites

    names = {
        str(item.get("domain") or "").strip().rstrip(".").lower()
        for item in [*list_domains(), *list_sites()]
    }
    return sorted(name for name in names if name and "." in name)


def sync_routes() -> dict[str, Any]:
    """Atomically rewrite Traefik routes to the single Roundcube service."""
    path = _dynamic_config_path()
    features = load_features()
    enabled = bool(features.get("web") and features.get("mail"))
    hostnames = routed_hostnames() if enabled else []

    lines = [
        "# Generated by mrmpanel. Do not edit; domain/site changes replace it.",
        "http:",
        "  middlewares:",
        "    webmail-force-https:",
        "      redirectScheme:",
        "        scheme: https",
        "        permanent: true",
        "    webmail-add-slash:",
        "      redirectRegex:",
        r'        regex: "^https://([^/]+)/webmail$"',
        r'        replacement: "https://${1}/webmail/"',
        "        permanent: true",
        "    webmail-strip-prefix:",
        "      stripPrefix:",
        "        prefixes:",
        "          - /webmail",
        "  routers:",
    ]

    for hostname in hostnames:
        router = _router_name(hostname)
        rule = f"Host(`{hostname}`) && PathPrefix(`/webmail`)"
        lines.extend(
            [
                f"    {router}-http:",
                f"      rule: \"{rule}\"",
                "      entryPoints:",
                "        - web",
                "      priority: 1000",
                "      middlewares:",
                "        - webmail-force-https",
                "      service: mrmpanel-webmail",
                f"    {router}:",
                f"      rule: \"{rule}\"",
                "      entryPoints:",
                "        - websecure",
                "      priority: 1000",
                "      middlewares:",
                "        - webmail-add-slash",
                "        - webmail-strip-prefix",
                "      service: mrmpanel-webmail",
                "      tls:",
                "        certResolver: letsencrypt",
            ]
        )

    lines.extend(
        [
            "  services:",
            "    mrmpanel-webmail:",
            "      loadBalancer:",
            "        servers:",
            '          - url: "http://mrmpanel-roundcube:80"',
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text("\n".join(lines), encoding="utf-8")
    tmp.replace(path)
    return {"enabled": enabled, "hostnames": hostnames, "path": str(path)}
